/** Walk the entire journey and capture confirmation. */
import { chromium } from '@playwright/test'
const [out, h = '800'] = process.argv.slice(2)
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: Number(h) } })
p.on('pageerror', e => console.log('PAGE ERROR:', e.message))
await p.goto('http://localhost:5173/product/voltaren', { waitUntil: 'networkidle' })
await p.getByRole('button', { name: /Ihre PLZ/ }).click()
await p.getByLabel('Postleitzahl').fill('22083')
await p.getByRole('button', { name: 'OK' }).click()
await p.getByRole('button', { name: /In den Warenkorb/ }).click()
await p.waitForURL('**/basket')
await p.locator('.suggestion-card').filter({ has: p.locator('a[href="/product/bepanthen"]') })
  .locator('.suggestion-card__add').click()
await p.waitForTimeout(200)
const basketPromise = await p.locator('.basket-delivery-summary').innerText()
await p.getByRole('button', { name: 'Zur Kasse' }).click()
await p.waitForURL('**/checkout/address')
await p.getByRole('button', { name: 'Weiter zum Versand' }).click()
await p.waitForURL('**/checkout/shipping')
const shippingText = await p.locator('.shipping-block').first().innerText()
await p.getByRole('button', { name: 'Weiter zur Zahlungsart' }).click()
await p.waitForURL('**/checkout/payment')
await p.getByRole('button', { name: 'Weiter zur Prüfung' }).click()
await p.waitForURL('**/checkout/review')
const reviewText = await p.locator('.shipping-block').first().innerText()
await p.getByRole('button', { name: 'Zahlungspflichtig bestellen' }).click()
await p.waitForURL('**/confirmation/**')
await p.waitForTimeout(200)
console.log('--- BASKET ---\n' + basketPromise)
console.log('--- SHIPPING (shipment 1) ---\n' + shippingText)
console.log('--- REVIEW (shipment 1) ---\n' + reviewText)
console.log('--- CONFIRMATION ---\n' + await p.locator('main').innerText())
await p.screenshot({ path: out })
await b.close()
